MineLib/Executables/MineLib.Server.WebSite/Controllers/ApiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MineLib.Server.WebSite.Models.ApiViewModels;
using MineLib.Server.WebSite.Repositories;
using System;
using System.Linq;
using System.Net;

namespace MineLib.Server.WebSite.Controllers
{
    public sealed class ApiController : Controller
    {
        private readonly IClassicServersRepository _classicServerRepository;
        private readonly ILogger _logger;

        public ApiController(IClassicServersRepository classicServerRepository, ILogger<ApiController> logger)
        {
            _classicServerRepository = classicServerRepository ?? throw new ArgumentNullException(nameof(classicServerRepository));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        [HttpGet("{data}")]
        public ActionResult Server(string data)
        {
            _logger.LogInformation("{Type}: Received /api/server/{data} request", GetType().FullName, data);

            var hashes = data.Split(',', StringSplitOptions.RemoveEmptyEntries);
            if(hashes.Length == 0)
                return Content("");

            var servers = _classicServerRepository.List()
                .Where(s => hashes.Contains(s.Hash) && DateTimeOffset.UtcNow < s.LastUpdate + TimeSpan.FromMinutes(2))
                .Select(s =>
                {
                    var ip = IPAddress.Parse(s.IP);
                    s.IP = ip.IsIPv4MappedToIPv6 ? ip.MapToIPv4().ToString() : ip.MapToIPv6().ToString();
                    return s;
                });

            return View("Servers", new ServerViewModel { Servers = servers });
        }

        public IActionResult Servers()
        {
            _logger.LogInformation("{Type}: Received /api/servers request", GetType().FullName);

            var servers = _classicServerRepository.List()
                .Where(s => DateTimeOffset.UtcNow < s.LastUpdate + TimeSpan.FromMinutes(2))
                .Select(s =>
                {
                    var ip = IPAddress.Parse(s.IP);
                    s.IP = ip.IsIPv4MappedToIPv6 ? ip.MapToIPv4().ToString() : ip.MapToIPv6().ToString();
                    return s;
                });

            return View(new ServerViewModel { Servers = servers });
        }
    }
}

MineLib/Executables/MineLib.Server.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"]</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">MineLib</a>
                </div>
                <div class="navbar-collapse collapse">
                    @*
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    </ul>
                    *@
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Api" asp-action="Servers" class="navbar-brand">Classic Servers</a></li>
                    </ul>

                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018-2020, MineLib Project</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=">
            </script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>